### ISSUE TITLE
Creepers Perpetually Making Firework Noises and Animations in World

### ISSUE THREAD

**Issue by phrantick99** [henkelmax/anti-mob-griefing#2]
**Bug description**
I'm playing Delivery, Inc. modpack and this mod is in there. From what I understand the creepers aren't supposed to be making the animations and noises of fireworks all the time and only when they explode.  This was not happening with me in my world and was only remedied when I changed the config options to not have them have fireworks at all. 

These are the logs of up until I turned off the option. Couldn't play it much before because the animations would give me migraines. 

**Steps to reproduce the issue**
1. Just log in the game
2. Find creeper
3. See strobe lights
4. log off

**Expected behavior**
Not have creepers perpetually have fireworks noises and animations.

**Log files**
https://gist.github.com/phrantick99/9124456a27ee4f79e777e60588044af3

**Versions**
- Minecraft version 1.16.5
- Forge version 36.1.0
- Mod version 1.0.0

**Other mods**
modpack installed: Delivery Inc

**Comment by henkelmax** [comment]
Not sure what you sent, but its not your logs.

**Comment by henkelmax** [comment]
In addition to your logs it would be great having a video of it happening.

**Comment by phrantick99** [comment]
it isn't in the folder labeled logs? That's the stuff I copied and pasted
in that link.

**Comment by henkelmax** [comment]
You have to upload the latest.log or debug.log the other files are compressed files. GitHub gist only works with plain text files.

**Comment by phrantick99** [comment]
Here's video of what is happening. https://youtu.be/y1pPnAPW5VQ

latest.log of a new default world https://gist.github.com/phrantick99/9157ce05ca86cfed7ab1622c98f91dd8

**Comment by henkelmax** [comment]
Thank you!
Are you playing on a server or singleplayer?
Have you added any additional mods except the mods in the modpack?
Does that happen if you create a new world?

**Comment by phrantick99** [comment]
Single player, added OptiFine_1.16.5_HD_U_G7 and ftb-ultimine-1605.2.0-build.25-forge and yes, the video was a fresh world.

**Comment by henkelmax** [comment]
Can you try it without any of these mods?

**Comment by phrantick99** [comment]
Tried first without ultmine, still did it; then tried without Optifine and it stopped.  So it looks like it's a weird interaction with Optifine and anti-mob griefing.  
I can set the option in the anti-mob griefing config to false and I can use both mods without the creeper rave.

**Comment by henkelmax** [comment]
OptiFine is veeeery buggy when it comes to modded minecraft... I would always recommend not using OptiFine when playing a modpack.

**Comment by henkelmax** [comment]
I fixed it in the latest version.
But I still don't recommend using OptiFine with Delivery Inc.
