### ISSUE TITLE
Incompatibility with Experienced Anvils

### ISSUE THREAD

**Issue by diablo050189** [henkelmax/anti-mob-griefing#6]
**Bug description**
As of version 1.16.5-1.0.3 my server and client crash when launched if [experienced anvils](https://www.curseforge.com/minecraft/mc-mods/expanvils) is also present.

**Steps to reproduce the issue**
1. Add AMG1.0.3 and expanvils to mods folder.
2. Launch Minecraft client or server and it will crash.

**Expected behavior**
Server and client not to crash.

**Log files**
[latest.log](https://pastebin.com/QhimVRvb)

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.2.0
- Mod version: 1.0.3

**Other mods**
[Experienced Anvils](https://www.curseforge.com/minecraft/mc-mods/expanvils)

**Comment by henkelmax** [comment]
I can't find any error related to this mod. Please test if this also occurs if only experienced anvils is installed.

**Comment by diablo050189** [comment]
Server has been running fine with experienced anvils and AMG1.0.2 but as soon as I updated to 1.0.3 then it crashes both server and client. Tried 1.0.3 with only these 2 mods in mods folder and it still crashes but works fine if I remove either of the 2 mods or downgrade AMG to 1.0.2.

**Comment by henkelmax** [comment]
Does AMG work on its own?

**Comment by diablo050189** [comment]
Yes. AMG 1.0.2 and 1.0.3 both work by themselves. AMG 1.0.2 works with expanvils. AMG 1.0.3 crashes when used with expanvils.

**Comment by henkelmax** [comment]
This issue seems to originate from Experienced anvils: 
`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.expanvils.json:RepairContainerMixin] from phase [DEFAULT] in config [mixins.expanvils.json] FAILED during APPLY`

Please report this issue to their issue tracker

**Comment by diablo050189** [comment]
Alright I reported the issue to them now. Just figured I would start here since updating your mod is what introduced the issue.

**Comment by henkelmax** [comment]
Yeah... Really weird, but the error does not mention AMG...
