### ISSUE TITLE
Description Typo

### ISSUE THREAD

**Issue by oyuno-miyumi** [henkelmax/anti-mob-griefing#7]
**Please read the [FAQ](https://modrepo.de/minecraft/antimobgriefing/faq) before submitting a bug report!**

**Bug description**
On both the Curseforge entry and the modrepo entry, the description for "creeper.firework.enabled" is "Disable crop trampling"

**Steps to reproduce the issue**
1. Go to the mod page
2. Click on "Description" or Overview"
3. Scroll down to '"creeper.firework.enabled"

**Expected behavior**
A description inovlving something to do with fireworks from a creeper

**Log files**
N/A

**Versions**
N/A

**Other mods**
N/A

**Comment by henkelmax** [comment]
Thank you!
