### ISSUE TITLE
I can't find config

### ISSUE THREAD

**Issue by lee15322** [henkelmax/anti-mob-griefing#8]
I use this mod in Forge 1.18.1 Anti Mob Griefing
But,I can't find any config.In curseforge.

**Comment by henkelmax** [comment]
`.minecraft/saves/<your-world>/serverconfig/antimobgriefing-server.toml`

**Comment by imabr777** [comment]
I'm using this for a 1.18.2 Fabric server, cannot find the config file either. It's not in the ./config folder nor the ./world/serverconfig folder.

**Comment by henkelmax** [comment]
> I'm using this for a 1.18.2 Fabric server, cannot find the config file either. It's not in the ./config folder nor the ./world/serverconfig folder.

This is a forge mod
