### ISSUE TITLE
Question about mod licensing

### ISSUE THREAD

**Issue by fengshuo2004** [henkelmax/anti-mob-griefing#9]
First of all, thank you for making this mod, I've found it very useful for my modded server!

Could you please clarify what license applies to the source code of this mod by adding a LICENSE file to the repo, also state on Curseforge (currently set to "all rights reserved")? I'm creating a mcmod.cn entry for this mod and it'd be nice to know whether it is open source or not.

Another question, is this mod required on both the server and client side, or is client side installation optional?

**Comment by henkelmax** [comment]
If there is no license, this automatically means All Rights Reserved.

**Comment by fengshuo2004** [comment]
> If there is no license, this automatically means All Rights Reserved.

Got it.

What about my second question, is this mod required on both the server and client side, or is client side installation optional?

**Comment by henkelmax** [comment]
Both is required
